//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Truesight.Parser.Api
{
    public enum IILOpType
    {
        Nop,
        Break,
        Ldarg,
        Ldloc,
        Stloc,
        Ldarga,
        Starg,
        Ldloca,
        Ldc,
        Dup,
        Pop,
        Jmp,
        Call,
        Ret,
        Branch,
        Switch,
        Ldind,
        Stind,
        Operator,
        Cast,
        Cpobj,
        New,
        Isinst,
        Throw,
        Ldfld,
        Ldflda,
        Stfld,
        Ldlen,
        Ldelema,
        Ldelem,
        Stelem,
        Refanyval,
        Ckfinite,
        Mkrefany,
        Endfinally,
        Arglist,
        Ldftn,
        Localloc,
        Endfilter,
        Unaligned,
        Volatile,
        Tail,
        Constrained,
        Cpblk,
        Initblk,
        Rethrow,
        Sizeof,
        Refanytype,
        Readonly
    }
}