//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Truesight.Parser.Api.Ops
{
    public enum OperatorType
    {
        Add,
        And,
        Divide,
        Equal,
        GreaterThan,
        GreaterThanOrEqual,
        LeftShift,
        LessThan,
        LessThanOrEqual,
        Modulo,
        Multiply,
        Negate,
        Not,
        NotEqual,
        Or,
        RightShift,
        Subtract,
        Xor
    }
}